# This is a basic workflow to help you get started with Actions

name: Build

on:
  push:
    branches: [ main, stable ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install GTK
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt install libgtk-3-dev
      - uses: actions/checkout@v2
      - name: Build (release)
        run: cargo build --release
      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: target
          # An explicit key for restoring and saving the cache
          key: deps-build
