name: Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install GTK
      run: sudo apt install libgtk-3-dev
    - uses: actions/checkout@v2
    - name: Run clippy
      run: cargo clippy
    - name: Cache
      uses: actions/cache@v2.1.3
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: target
        # An explicit key for restoring and saving the cache
        key: deps-lint
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install GTK
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt install libgtk-3-dev
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test
    - name: Cache
      uses: actions/cache@v2.1.3
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: target
        # An explicit key for restoring and saving the cache
        key: deps-test
